#!/bin/bash
modprobe rpi_shiftreg_rtdm
modprobe audio_rtdm audio_buffer_size=64

DEVICE="/dev/rtdm/audio_rtdm"

if [ -e $DEVICE ]
then
    echo "audio_rtdm loaded"
    fw_setenv boot_count 0
    sync
    exit 0
else
    echo "audio_rtdm failed"
    exit 1
fi
