#!/bin/bash
modprobe rpi_shiftreg_rtdm
modprobe audio_rtdm

DEVICE="/dev/rtdm/audio_rtdm"

if [ -e $DEVICE ]
then
    echo "audio_rtdm loaded"
    exit 0
else
    echo "audio_rtdm failed"
    exit 1
fi
