#!/bin/bash
GPIO_RED=12
GPIO_GREEN=26
GPIODIR_RED=/sys/class/gpio/gpio$GPIO_RED
GPIODIR_GREEN=/sys/class/gpio/gpio$GPIO_GREEN

if [ ! -e "$GPIODIR_RED" ]
then
	echo $GPIO_RED > /sys/class/gpio/export
else
	echo "GPIO_RED already exported"
fi

if [ ! -e "$GPIODIR_GREEN" ]
then
	echo $GPIO_GREEN > /sys/class/gpio/export
else
	echo "GPIO_GREEN already exported"
fi

echo out > $GPIODIR_RED/direction
echo out > $GPIODIR_GREEN/direction

while ( true );
	do echo 1 > $GPIODIR_RED/value;
        echo 1 > $GPIODIR_GREEN/value;
	sleep 1;
	echo 0 > $GPIODIR_RED/value;
        echo 0 > $GPIODIR_GREEN/value;
	sleep 1;
done;
