#!/bin/bash
modprobe shiftreg_rtdm adc_chans_per_tick=4
modprobe audio_rtdm audio_buffer_size=64
modprobe i2c_dev
rfkill unblock all

# Set CPU Speed
echo userspace > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq > /sys/devices/system/cpu/cpu0/cpufreq/scaling_setspeed
sync

DEVICE="/dev/rtdm/audio_rtdm"

if [ -e $DEVICE ]
then
    echo "audio_rtdm loaded"
    fw_setenv boot_count 0
    sync
    umount /boot
    exit 0
else
    echo "audio_rtdm failed"
    exit 1
fi
