DEPENDS += "xenomai-lib"
PV = "0.2.0+${SRCREV}"
SRCREV = "c2c82cd2ebd29cce48923ab43513a1df6d1ed381"

EXTRA_OECMAKE = "\
    -DCMAKE_BUILD_TYPE=Release \
    -DWITH_UNIT_TESTS=FALSE \
    -DWITH_GPIO_LOGIC=TRUE \
    -DXENOMAI_BASE_DIR=${WORKDIR}/recipe-sysroot/usr/xenomai \
    -DGPIO_PROTOCOL_BUILD_CLIENT_LIB=TRUE \
    -DGPIO_LOG_LEVEL=error \
    -DCMAKE_SKIP_RPATH=TRUE \
"